env:
  SHOULD_PUBLISH: 'true'
  IS_RELEASE: 'false'
name: Usig custom action
on: [push]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        if: ${{ env.SHOULD_PUBLISH == 'true' && env.IS_RELEASE == 'false'}}
        run: echo $(git rev-parse --short HEAD)
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build TEST environment name
        id: deploy-test-environment
        run: |
          TEST_ENVIRONMENT_NAME="fcp-auto-testing"
          echo "TEST_ENVIRONMENT_NAME=${TEST_ENVIRONMENT_NAME}" >> $GITHUB_ENV 

      - name: Test env
        run: echo environmentName=${TEST_ENVIRONMENT_NAME}
