name: usdig custom action
on: [push]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v1
    - uses: LeonidKovbasiuk/custom-action@master
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
