env:
  SHOULD_PUBLISH: 'true'
  IS_RELEASE: 'false'
name: Usig custom action
on: [push]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      if: ${{ env.SHOULD_PUBLISH == 'true' && env.IS_RELEASE == 'false'}}
      run: echo "Ok!"
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
