name: Usig custom action
on: [push]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Run Action
      uses: LeonidKovbasiuk/custom-action@v1.0.2
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
