name: Usig custom action
on: [push]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: LeonidKovbasiuk/custom-action@master
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
