name: Usig custom action
on: [push]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v1
    - uses: LeonidKovbasiuk/custom-action@master
=======
    - uses: actions/checkout@v2
    - uses: LeonidKovbasiuk/custom-action@latest
>>>>>>> ac810d6 (update yml file)
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
